slice_name: "\u0430\u0432\u0433 \u0438\u043D\u043A\u0430\u043C \u043F\u043E \u0432\
  \u043E\u0437\u0440\u0430\u0441\u0442\u0443"
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  datasource: 25__table
  viz_type: echarts_timeseries_bar
  slice_id: 108
  x_axis: PERSON_AGE
  x_axis_sort: AVG(INCOME)
  x_axis_sort_asc: false
  x_axis_sort_series: name
  x_axis_sort_series_ascending: true
  metrics:
  - expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: INCOME
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 776
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: DOUBLE PRECISION
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    aggregate: AVG
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: true
    label: "\u041F\u0440\u0438\u0431\u044B\u043B\u044C"
    optionName: metric_gbuhqrsj9lt_xoooh31afe
  groupby: []
  adhoc_filters: []
  timeseries_limit_metric:
    aggregate: AVG
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: INCOME
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 776
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: DOUBLE PRECISION
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: AVG(INCOME)
    optionName: metric_8pk2kn58xt6_zk9pcihgf7
    sqlExpression: null
  order_desc: false
  row_limit: 10000
  truncate_metric: true
  show_empty_columns: false
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  orientation: horizontal
  x_axis_title: ''
  x_axis_title_margin: 15
  y_axis_title: ''
  y_axis_title_margin: 15
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: supersetColors
  only_total: true
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  xAxisLabelRotation: 0
  y_axis_format: SMART_NUMBER
  logAxis: false
  minorSplitLine: false
  truncateYAxis: false
  y_axis_bounds:
  - null
  - null
  rich_tooltip: true
  tooltipTimeFormat: smart_date
  extra_form_data: {}
  dashboards:
  - 11
  - 14
query_context: "{\"datasource\":{\"id\":25,\"type\":\"table\"},\"force\":false,\"\
  queries\":[{\"filters\":[],\"extras\":{\"having\":\"\",\"where\":\"\"},\"applied_time_extras\"\
  :{},\"columns\":[{\"columnType\":\"BASE_AXIS\",\"sqlExpression\":\"PERSON_AGE\"\
  ,\"label\":\"PERSON_AGE\",\"expressionType\":\"SQL\"}],\"metrics\":[{\"expressionType\"\
  :\"SIMPLE\",\"column\":{\"advanced_data_type\":null,\"certification_details\":null,\"\
  certified_by\":null,\"column_name\":\"INCOME\",\"description\":null,\"expression\"\
  :null,\"filterable\":true,\"groupby\":true,\"id\":776,\"is_certified\":false,\"\
  is_dttm\":false,\"python_date_format\":null,\"type\":\"DOUBLE PRECISION\",\"type_generic\"\
  :0,\"verbose_name\":null,\"warning_markdown\":null},\"aggregate\":\"AVG\",\"sqlExpression\"\
  :null,\"datasourceWarning\":false,\"hasCustomLabel\":true,\"label\":\"\u041F\u0440\
  \u0438\u0431\u044B\u043B\u044C\",\"optionName\":\"metric_gbuhqrsj9lt_xoooh31afe\"\
  },{\"aggregate\":\"AVG\",\"column\":{\"advanced_data_type\":null,\"certification_details\"\
  :null,\"certified_by\":null,\"column_name\":\"INCOME\",\"description\":null,\"expression\"\
  :null,\"filterable\":true,\"groupby\":true,\"id\":776,\"is_certified\":false,\"\
  is_dttm\":false,\"python_date_format\":null,\"type\":\"DOUBLE PRECISION\",\"type_generic\"\
  :0,\"verbose_name\":null,\"warning_markdown\":null},\"datasourceWarning\":false,\"\
  expressionType\":\"SIMPLE\",\"hasCustomLabel\":false,\"label\":\"AVG(INCOME)\",\"\
  optionName\":\"metric_8pk2kn58xt6_zk9pcihgf7\",\"sqlExpression\":null}],\"orderby\"\
  :[[{\"aggregate\":\"AVG\",\"column\":{\"advanced_data_type\":null,\"certification_details\"\
  :null,\"certified_by\":null,\"column_name\":\"INCOME\",\"description\":null,\"expression\"\
  :null,\"filterable\":true,\"groupby\":true,\"id\":776,\"is_certified\":false,\"\
  is_dttm\":false,\"python_date_format\":null,\"type\":\"DOUBLE PRECISION\",\"type_generic\"\
  :0,\"verbose_name\":null,\"warning_markdown\":null},\"datasourceWarning\":false,\"\
  expressionType\":\"SIMPLE\",\"hasCustomLabel\":false,\"label\":\"AVG(INCOME)\",\"\
  optionName\":\"metric_8pk2kn58xt6_zk9pcihgf7\",\"sqlExpression\":null},true]],\"\
  annotation_layers\":[],\"row_limit\":10000,\"series_columns\":[],\"series_limit\"\
  :0,\"series_limit_metric\":{\"aggregate\":\"AVG\",\"column\":{\"advanced_data_type\"\
  :null,\"certification_details\":null,\"certified_by\":null,\"column_name\":\"INCOME\"\
  ,\"description\":null,\"expression\":null,\"filterable\":true,\"groupby\":true,\"\
  id\":776,\"is_certified\":false,\"is_dttm\":false,\"python_date_format\":null,\"\
  type\":\"DOUBLE PRECISION\",\"type_generic\":0,\"verbose_name\":null,\"warning_markdown\"\
  :null},\"datasourceWarning\":false,\"expressionType\":\"SIMPLE\",\"hasCustomLabel\"\
  :false,\"label\":\"AVG(INCOME)\",\"optionName\":\"metric_8pk2kn58xt6_zk9pcihgf7\"\
  ,\"sqlExpression\":null},\"order_desc\":false,\"url_params\":{},\"custom_params\"\
  :{},\"custom_form_data\":{},\"time_offsets\":[],\"post_processing\":[{\"operation\"\
  :\"pivot\",\"options\":{\"index\":[\"PERSON_AGE\"],\"columns\":[],\"aggregates\"\
  :{\"\u041F\u0440\u0438\u0431\u044B\u043B\u044C\":{\"operator\":\"mean\"},\"AVG(INCOME)\"\
  :{\"operator\":\"mean\"}},\"drop_missing_columns\":true}},{\"operation\":\"sort\"\
  ,\"options\":{\"by\":\"AVG(INCOME)\",\"ascending\":false}},{\"operation\":\"flatten\"\
  }]}],\"form_data\":{\"datasource\":\"25__table\",\"viz_type\":\"echarts_timeseries_bar\"\
  ,\"slice_id\":108,\"x_axis\":\"PERSON_AGE\",\"x_axis_sort\":\"AVG(INCOME)\",\"x_axis_sort_asc\"\
  :false,\"x_axis_sort_series\":\"name\",\"x_axis_sort_series_ascending\":true,\"\
  metrics\":[{\"expressionType\":\"SIMPLE\",\"column\":{\"advanced_data_type\":null,\"\
  certification_details\":null,\"certified_by\":null,\"column_name\":\"INCOME\",\"\
  description\":null,\"expression\":null,\"filterable\":true,\"groupby\":true,\"id\"\
  :776,\"is_certified\":false,\"is_dttm\":false,\"python_date_format\":null,\"type\"\
  :\"DOUBLE PRECISION\",\"type_generic\":0,\"verbose_name\":null,\"warning_markdown\"\
  :null},\"aggregate\":\"AVG\",\"sqlExpression\":null,\"datasourceWarning\":false,\"\
  hasCustomLabel\":true,\"label\":\"\u041F\u0440\u0438\u0431\u044B\u043B\u044C\",\"\
  optionName\":\"metric_gbuhqrsj9lt_xoooh31afe\"}],\"groupby\":[],\"adhoc_filters\"\
  :[],\"timeseries_limit_metric\":{\"aggregate\":\"AVG\",\"column\":{\"advanced_data_type\"\
  :null,\"certification_details\":null,\"certified_by\":null,\"column_name\":\"INCOME\"\
  ,\"description\":null,\"expression\":null,\"filterable\":true,\"groupby\":true,\"\
  id\":776,\"is_certified\":false,\"is_dttm\":false,\"python_date_format\":null,\"\
  type\":\"DOUBLE PRECISION\",\"type_generic\":0,\"verbose_name\":null,\"warning_markdown\"\
  :null},\"datasourceWarning\":false,\"expressionType\":\"SIMPLE\",\"hasCustomLabel\"\
  :false,\"label\":\"AVG(INCOME)\",\"optionName\":\"metric_8pk2kn58xt6_zk9pcihgf7\"\
  ,\"sqlExpression\":null},\"order_desc\":false,\"row_limit\":10000,\"truncate_metric\"\
  :true,\"show_empty_columns\":false,\"comparison_type\":\"values\",\"annotation_layers\"\
  :[],\"forecastPeriods\":10,\"forecastInterval\":0.8,\"orientation\":\"horizontal\"\
  ,\"x_axis_title\":\"\",\"x_axis_title_margin\":15,\"y_axis_title\":\"\",\"y_axis_title_margin\"\
  :15,\"y_axis_title_position\":\"Left\",\"sort_series_type\":\"sum\",\"color_scheme\"\
  :\"supersetColors\",\"only_total\":true,\"show_legend\":true,\"legendType\":\"scroll\"\
  ,\"legendOrientation\":\"top\",\"x_axis_time_format\":\"smart_date\",\"xAxisLabelRotation\"\
  :0,\"y_axis_format\":\"SMART_NUMBER\",\"logAxis\":false,\"minorSplitLine\":false,\"\
  truncateYAxis\":false,\"y_axis_bounds\":[null,null],\"rich_tooltip\":true,\"tooltipTimeFormat\"\
  :\"smart_date\",\"extra_form_data\":{},\"dashboards\":[11,14],\"force\":false,\"\
  result_format\":\"json\",\"result_type\":\"full\"},\"result_format\":\"json\",\"\
  result_type\":\"full\"}"
cache_timeout: null
uuid: 1bd5a1d8-6868-48a7-9b34-dd42cc49bf52
version: 1.0.0
dataset_uuid: d5443528-76be-411a-9ef5-9175e661a389
