slice_name: Coun type of property
description: null
certified_by: null
certification_details: null
viz_type: pie
params:
  datasource: 26__table
  viz_type: pie
  slice_id: 104
  groupby:
  - TYPE_PROPERTY
  metric:
    aggregate: COUNT
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: TYPE_PROPERTY
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 764
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: TEXT
      type_generic: 1
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: COUNT(TYPE_PROPERTY)
    optionName: metric_xmonvaiyr7n_qnek3x4h5ij
    sqlExpression: null
  adhoc_filters: []
  row_limit: 5000
  sort_by_metric: true
  color_scheme: supersetColors
  show_labels_threshold: 5
  show_legend: true
  legendType: scroll
  legendOrientation: top
  label_type: key
  number_format: SMART_NUMBER
  date_format: smart_date
  show_labels: true
  labels_outside: true
  outerRadius: 70
  innerRadius: 30
  extra_form_data: {}
  dashboards:
  - 12
query_context: null
cache_timeout: null
uuid: c30ab4e1-6931-408d-b480-518d87f31ece
version: 1.0.0
dataset_uuid: 97d172ee-ebcc-4405-a83e-e1a863bd4f82
