slice_name: Districts
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  datasource: 24__table
  viz_type: table
  slice_id: 269
  query_mode: aggregate
  groupby:
  - DISTRICT_NAME
  time_grain_sqla: P1D
  temporal_columns_lookup: {}
  metrics:
  - expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: PATIENT_ID
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 773
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: BIGINT
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    aggregate: COUNT
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: true
    label: "\u041A\u043E\u043B\u0438\u0447\u0435\u0441\u0442\u0432\u043E \u041F\u043E\
      \u043A\u0443\u043F\u0430\u0442\u0435\u043B\u0435\u0439 \u041F\u0440\u0435\u043F\
      \u0430\u0440\u0430\u0442\u043E\u0432"
    optionName: metric_eygkqwny137_2wyqigmshvi
  all_columns: []
  percent_metrics: []
  adhoc_filters: []
  order_by_cols: []
  row_limit: 1000
  server_page_length: 10
  order_desc: true
  table_timestamp_format: smart_date
  show_cell_bars: true
  color_pn: true
  extra_form_data: {}
  dashboards:
  - 13
query_context: null
cache_timeout: null
uuid: 48c8c081-c7f2-498d-80ba-fd0bf05a96c3
version: 1.0.0
dataset_uuid: 0fa6b8b7-d129-448f-8c39-4af76d5fa0c9
