slice_name: Number of properties
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  datasource: 26__table
  viz_type: big_number_total
  metric:
    expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: TYPE_PROPERTY
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 764
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: TEXT
      type_generic: 1
      verbose_name: null
      warning_markdown: null
    aggregate: COUNT
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: false
    label: COUNT(TYPE_PROPERTY)
    optionName: metric_py7jwiut1ws_dptatgm6f5n
  adhoc_filters: []
  header_font_size: 0.4
  subheader_font_size: 0.15
  y_axis_format: SMART_NUMBER
  time_format: smart_date
  extra_form_data: {}
  dashboards:
  - 12
query_context: null
cache_timeout: null
uuid: 84d2a2f8-fbad-40ea-ad03-689d557e81f9
version: 1.0.0
dataset_uuid: 97d172ee-ebcc-4405-a83e-e1a863bd4f82
