slice_name: 'Number of properties over regions '
description: null
certified_by: null
certification_details: null
viz_type: pie
params:
  datasource: 26__table
  viz_type: pie
  groupby:
  - REGION
  metric:
    expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: TYPE_PROPERTY
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 764
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: TEXT
      type_generic: 1
      verbose_name: null
      warning_markdown: null
    aggregate: COUNT
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: false
    label: COUNT(TYPE_PROPERTY)
    optionName: metric_f2pm9l3fjvw_jqyqwk1hxio
  adhoc_filters: []
  row_limit: 100
  sort_by_metric: true
  color_scheme: supersetColors
  show_labels_threshold: 5
  show_legend: true
  legendType: scroll
  legendOrientation: top
  label_type: key
  number_format: SMART_NUMBER
  date_format: smart_date
  show_labels: true
  labels_outside: true
  outerRadius: 70
  innerRadius: 30
  extra_form_data: {}
  dashboards:
  - 12
query_context: null
cache_timeout: null
uuid: 67ae403d-8cd6-47c6-99e9-ad9701b61ecc
version: 1.0.0
dataset_uuid: 97d172ee-ebcc-4405-a83e-e1a863bd4f82
