slice_name: Total Number of Customers
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  datasource: 24__table
  viz_type: big_number_total
  metric:
    expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: PATIENT_ID
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 773
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: BIGINT
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    aggregate: COUNT
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: false
    label: COUNT(PATIENT_ID)
    optionName: metric_e7v1slmqx7r_b112r48nw1m
  adhoc_filters: []
  header_font_size: 0.4
  subheader_font_size: 0.15
  y_axis_format: SMART_NUMBER
  time_format: smart_date
  extra_form_data: {}
  dashboards:
  - 13
query_context: null
cache_timeout: null
uuid: c736ce97-fd6e-4827-9855-33580b877fe6
version: 1.0.0
dataset_uuid: 0fa6b8b7-d129-448f-8c39-4af76d5fa0c9
